### ISSUE TITLE
Exception with Azure authority

### ISSUE THREAD

**Issue by Apteryx0** [jenkinsci/oic-auth-plugin#10]
I configured the plugin to use with my Azure authority and got he below stack trace - my naive guess is that the code is assuming there is a field that only Google returns....:

This is our end-point configuration (available at https://sts.windows.net/226151a9-bcce-47cc-b359-54b1c9041a44/.well-known/openid-configuration)
```
{
   "frontchannel_logout_supported" : true,
   "claims_supported" : [
      "sub",
      "iss",
      "cloud_instance_name",
      "aud",
      "exp",
      "iat",
      "auth_time",
      "acr",
      "amr",
      "nonce",
      "email",
      "given_name",
      "family_name",
      "nickname"
   ],
   "jwks_uri" : "https://login.windows.net/common/discovery/keys",
   "microsoft_multi_refresh_token" : true,
   "token_endpoint" : "https://login.windows.net/226151a9-bcce-47cc-b359-54b1c9041a44/oauth2/token",
   "id_token_signing_alg_values_supported" : [
      "RS256"
   ],
   "cloud_instance_name" : "microsoftonline.com",
   "authorization_endpoint" : "https://login.windows.net/226151a9-bcce-47cc-b359-54b1c9041a44/oauth2/authorize",
   "scopes_supported" : [
      "openid"
   ],
   "cloud_graph_host_name" : "graph.windows.net",
   "userinfo_endpoint" : "https://login.windows.net/226151a9-bcce-47cc-b359-54b1c9041a44/openid/userinfo",
   "issuer" : "https://sts.windows.net/226151a9-bcce-47cc-b359-54b1c9041a44/",
   "token_endpoint_auth_methods_supported" : [
      "client_secret_post",
      "private_key_jwt"
   ],
   "response_types_supported" : [
      "code",
      "id_token",
      "code id_token",
      "token id_token",
      "token"
   ],
   "http_logout_supported" : true,
   "subject_types_supported" : [
      "pairwise"
   ],
   "response_modes_supported" : [
      "query",
      "fragment",
      "form_post"
   ],
   "end_session_endpoint" : "https://login.windows.net/226151a9-bcce-47cc-b359-54b1c9041a44/oauth2/logout",
   "check_session_iframe" : "https://login.windows.net/226151a9-bcce-47cc-b359-54b1c9041a44/oauth2/checksession",
   "tenant_region_scope" : "NA"
}
```

```
Stack trace

javax.servlet.ServletException: java.lang.IllegalArgumentException: key expires_in
	at org.kohsuke.stapler.Stapler.tryInvoke(Stapler.java:796)
	at org.kohsuke.stapler.Stapler.invoke(Stapler.java:876)
	at org.kohsuke.stapler.MetaClass$3.doDispatch(MetaClass.java:197)
	at org.kohsuke.stapler.NameBasedDispatcher.dispatch(NameBasedDispatcher.java:58)
	at org.kohsuke.stapler.Stapler.tryInvoke(Stapler.java:746)
	at org.kohsuke.stapler.Stapler.invoke(Stapler.java:876)
	at org.kohsuke.stapler.Stapler.invoke(Stapler.java:649)
	at org.kohsuke.stapler.Stapler.service(Stapler.java:238)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:812)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1669)
	at hudson.util.PluginServletFilter$1.doFilter(PluginServletFilter.java:135)
	at com.smartcodeltd.jenkinsci.plugin.assetbundler.filters.LessCSS.doFilter(LessCSS.java:46)
	at hudson.util.PluginServletFilter$1.doFilter(PluginServletFilter.java:132)
	at hudson.plugins.greenballs.GreenBallFilter.doFilter(GreenBallFilter.java:59)
	at hudson.util.PluginServletFilter$1.doFilter(PluginServletFilter.java:132)
	at hudson.util.PluginServletFilter.doFilter(PluginServletFilter.java:126)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
	at hudson.security.csrf.CrumbFilter.doFilter(CrumbFilter.java:49)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:84)
	at hudson.security.UnwrapSecurityExceptionFilter.doFilter(UnwrapSecurityExceptionFilter.java:51)
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
	at jenkins.security.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:117)
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
	at org.acegisecurity.providers.anonymous.AnonymousProcessingFilter.doFilter(AnonymousProcessingFilter.java:125)
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
	at org.acegisecurity.ui.rememberme.RememberMeProcessingFilter.doFilter(RememberMeProcessingFilter.java:135)
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
	at org.acegisecurity.ui.AbstractProcessingFilter.doFilter(AbstractProcessingFilter.java:271)
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
	at jenkins.security.BasicHeaderProcessor.doFilter(BasicHeaderProcessor.java:93)
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
	at org.acegisecurity.context.HttpSessionContextIntegrationFilter.doFilter(HttpSessionContextIntegrationFilter.java:249)
	at hudson.security.HttpSessionContextIntegrationFilter2.doFilter(HttpSessionContextIntegrationFilter2.java:67)
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
	at hudson.security.ChainedServletFilter.doFilter(ChainedServletFilter.java:76)
	at hudson.security.HudsonFilter.doFilter(HudsonFilter.java:171)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
	at org.kohsuke.stapler.compression.CompressionFilter.doFilter(CompressionFilter.java:49)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
	at hudson.util.CharacterEncodingFilter.doFilter(CharacterEncodingFilter.java:82)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
	at org.kohsuke.stapler.DiagnosticThreadNameFilter.doFilter(DiagnosticThreadNameFilter.java:30)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:585)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:553)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:223)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1127)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1061)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
	at org.eclipse.jetty.server.Server.handle(Server.java:499)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:311)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:257)
	at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:544)
	at winstone.BoundedExecutorService$1.run(BoundedExecutorService.java:77)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalArgumentException: key expires_in
	at com.google.api.client.json.JsonParser.parseValue(JsonParser.java:889)
	at com.google.api.client.json.JsonParser.parse(JsonParser.java:382)
	at com.google.api.client.json.JsonParser.parse(JsonParser.java:355)
	at com.google.api.client.json.JsonObjectParser.parseAndClose(JsonObjectParser.java:87)
	at com.google.api.client.json.JsonObjectParser.parseAndClose(JsonObjectParser.java:81)
	at com.google.api.client.http.HttpResponse.parseAs(HttpResponse.java:459)
	at com.google.api.client.auth.openidconnect.IdTokenResponse.execute(IdTokenResponse.java:120)
	at org.jenkinsci.plugins.oic.OicSecurityRealm$2.onSuccess(OicSecurityRealm.java:200)
	at org.jenkinsci.plugins.oic.OicSession.doFinishLogin(OicSession.java:98)
	at org.jenkinsci.plugins.oic.OicSecurityRealm.doFinishLogin(OicSecurityRealm.java:294)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.kohsuke.stapler.Function$InstanceFunction.invoke(Function.java:335)
	at org.kohsuke.stapler.Function.bindAndInvoke(Function.java:175)
	at org.kohsuke.stapler.Function.bindAndInvokeAndServeResponse(Function.java:108)
	at org.kohsuke.stapler.MetaClass$1.doDispatch(MetaClass.java:124)
	at org.kohsuke.stapler.NameBasedDispatcher.dispatch(NameBasedDispatcher.java:58)
	at org.kohsuke.stapler.Stapler.tryInvoke(Stapler.java:746)
	... 62 more
Caused by: java.lang.IllegalArgumentException: key expires_in, field private java.lang.Long com.google.api.client.auth.oauth2.TokenResponse.expiresInSeconds
	at com.google.api.client.json.JsonParser.parseValue(JsonParser.java:889)
	at com.google.api.client.json.JsonParser.parse(JsonParser.java:472)
	at com.google.api.client.json.JsonParser.parseValue(JsonParser.java:781)
	... 81 more
Caused by: java.lang.IllegalArgumentException: number field formatted as a JSON string must use the @JsonString annotation
	at com.google.api.client.repackaged.com.google.common.base.Preconditions.checkArgument(Preconditions.java:125)
	at com.google.api.client.util.Preconditions.checkArgument(Preconditions.java:49)
	at com.google.api.client.json.JsonParser.parseValue(JsonParser.java:854)
	... 83 more
```

**Comment by dbsanfte** [comment]
I think the upgrade to 1.22 of the google auth clients will fix this. 

https://github.com/google/google-oauth-java-client/issues/62

**Comment by dbsanfte** [comment]
I noticed the plugin has been updated to use these new 1.22 plugins but hasn't been released, so there's no jar. Can we get a release done?

**Comment by thuandt** [comment]
@dbsanfte I try recompile oic-auth-plugin from here https://github.com/devopskube/oic-auth-plugin  but it's not works for me.

Can you share with me experience with Azure login?

Thanks

**Comment by Nagainos** [comment]
I need this plugin working! :)

**Comment by jamesabbottsmith** [comment]
Can we please get a new release of this plugin such that it works with AzureAD? It seems like @dbsanfte may have got it working, but that's not available to the rest of us.

**Comment by mjmbischoff** [comment]
@jamesabbottsmith as @dbsanfte mentioned the current google oauth client release(1.23) doesn't contain the fix:
"Edit: Actually nevermind, I spoke too soon. This is fixed in a fork of the google project, but not in the project itself. I had to hack the lib and compile my own version, as specified in the thread, and now my azure ad authentication works."

I think I can use a patched version of the oauth client in this plugin however. I'm working on a pull request.

**Comment by mjmbischoff** [comment]
Could only test for regression, if someone could test that it fixes the actual problem then that would be nice.

else going to assume it just works (tm)

**Comment by jamesabbottsmith** [comment]
@mjmbischoff I just tested this. It works for me. I was able to log in using my Azure AD account. Thanks very much. 😄

**Comment by danilina-wsib** [comment]
@jamesabbottsmith I get the following exception after I upgraded to v1.2. Can you share your securityRealm config?

java.lang.NumberFormatException: For input string: "null"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Long.parseLong(Long.java:589)
	at java.lang.Long.valueOf(Long.java:803)
	at com.google.api.client.auth.oauth2.TokenResponse.getExpiresInSeconds(TokenResponse.java:113)
	at com.google.api.client.auth.oauth2.Credential.setFromTokenResponse(Credential.java:542)
	at com.google.api.client.auth.oauth2.AuthorizationCodeFlow.createAndStoreCredential(AuthorizationCodeFlow.java:225)
	at org.jenkinsci.plugins.oic.OicSecurityRealm$3.onSuccess(OicSecurityRealm.java:349)
	at org.jenkinsci.plugins.oic.OicSession.doFinishLogin(OicSession.java:108)
	at org.jenkinsci.plugins.oic.OicSecurityRealm.doFinishLogin(OicSecurityRealm.java:544)
	at java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:627)
	at org.kohsuke.stapler.Function$MethodFunction.invoke(Function.java:343)
	at org.kohsuke.stapler.Function.bindAndInvoke(Function.java:184)
	at org.kohsuke.stapler.Function.bindAndInvokeAndServeResponse(Function.java:117)
	at org.kohsuke.stapler.MetaClass$1.doDispatch(MetaClass.java:129)
	at org.kohsuke.stapler.NameBasedDispatcher.dispatch(NameBasedDispatcher.java:58)
	at org.kohsuke.stapler.Stapler.tryInvoke(Stapler.java:715)

**Comment by mjmbischoff** [comment]
"expires_in
OPTIONAL. Expiration time of the Access Token in seconds since the response was generated."

Yeah my bad, added a test case for when it's not supplied at all. See if you can configure the provider to supply an expiration else wait for the next release.

**Comment by mjmbischoff** [comment]
Having slept on it. If the expires_in is not reported by the openid connect provider then you wouldn't hit the original bug, so downgrading pinning it on 1.1 should also work for now. I'll do a 1.3 bugfix release on Friday / Saturday

**Comment by mjmbischoff** [comment]
1.3 released containing the fix.
