### ISSUE TITLE
v4.350+ : java.lang.NullPointerException at PluginClassLoader for oic-auth//...(OicSecurityRealm.java:690)

### ISSUE THREAD

**Issue by Daryes** [jenkinsci/oic-auth-plugin#412]
### Jenkins and plugins versions report

<details>
  <summary>Environment</summary>

  
  ```text
Jenkins: 2.462.3
OS: Linux - 5.15.0-122-generic
System : 
Java: 11.0.24 - Ubuntu (OpenJDK 64-Bit Server VM)

Jenkins v2.462.3 LTS, fully upgraded as of 2024/10/05
---
credentials:1381.v2c3a_12074da_b_
credentials-binding:681.vf91669a_32e45
jackson2-api:2.17.0-379.v02de8ec9f64c
...
  ```
</details>

### What Operating System are you using (both controller, and any agents involved in the problem)?

Single Jenkins server, Ubuntu 22.04.5
Keycloak v21.1.2 on a separate server

### Reproduction steps

I'm getting this error since the oic-auth-plugin v4.350, same with v4.355 : 
Jenkins hangs immediately when connecting on the root page, and with the said error in the logs.
(cf after for the crash log)

Also, the following parameters are deleted from the `<securityRealm ... plugin="oic-auth@...">` section in  jenkins' config.xml file  :
```
    <tokenServerUrl>...</tokenServerUrl>
    <authorizationServerUrl>...</authorizationServerUrl>
    <userInfoServerUrl>...</userInfoServerUrl>
    <scopes>...</scopes>
    <endSessionEndpoint>...</endSessionEndpoint>
```
A diff confirm there was only a removal,  no other parameters in the section was updated nor inserted.

This happens even if fully logged off from the session directly on Keycloak side.
The escape hatch is also not accessible (too easy otherwise).

Just rolling back to oic-auth v4.346 with the deleted line back in the config.xml file is enough to have jenkins + oic authentication working again correctly.

### Expected Results

Not having Jenkins crashing when connecting on the home page, and able to log through OIC.

### Actual Results

**Crash error log :** 
<details>
  <summary>Jenkins error log</summary>

```
2024-10-05 20:42:49.448+0000 [id=105]   WARNING h.i.i.InstallUncaughtExceptionHandler#handleException: Caught unhandled exception with ID 38f9dea0-f2f3-465d-a017-8b3c162acb3a
java.lang.NullPointerException
        at PluginClassLoader for oic-auth//org.jenkinsci.plugins.oic.OicSecurityRealm.buildAuthorizationCodeFlow(OicSecurityRealm.java:690)
        at PluginClassLoader for oic-auth//org.jenkinsci.plugins.oic.OicSecurityRealm.doCommenceLogin(OicSecurityRealm.java:815)
        at java.base/java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:710)
        at org.kohsuke.stapler.Function$MethodFunction.invoke(Function.java:416)
        at org.kohsuke.stapler.Function$InstanceFunction.invoke(Function.java:429)
        at org.kohsuke.stapler.Function.bindAndInvoke(Function.java:211)
        at org.kohsuke.stapler.Function.bindAndInvokeAndServeResponse(Function.java:138)
        at org.kohsuke.stapler.MetaClass$11.doDispatch(MetaClass.java:644)
        at org.kohsuke.stapler.NameBasedDispatcher.dispatch(NameBasedDispatcher.java:61)
        at org.kohsuke.stapler.Stapler.tryInvoke(Stapler.java:827)
Caused: javax.servlet.ServletException
        at org.kohsuke.stapler.Stapler.tryInvoke(Stapler.java:878)
        at org.kohsuke.stapler.Stapler.invoke(Stapler.java:965)
        at org.kohsuke.stapler.MetaClass$2.doDispatch(MetaClass.java:244)
        at org.kohsuke.stapler.NameBasedDispatcher.dispatch(NameBasedDispatcher.java:61)
        at org.kohsuke.stapler.Stapler.tryInvoke(Stapler.java:827)
        at org.kohsuke.stapler.Stapler.invoke(Stapler.java:965)
        at org.kohsuke.stapler.Stapler.invoke(Stapler.java:747)
        at org.kohsuke.stapler.Stapler.service(Stapler.java:253)
        at Jenkins Main ClassLoader//javax.servlet.http.HttpServlet.service(HttpServlet.java:590)
        at Jenkins Main ClassLoader//org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:764)
        at Jenkins Main ClassLoader//org.eclipse.jetty.servlet.ServletHandler$ChainEnd.doFilter(ServletHandler.java:1665)
        at hudson.util.PluginServletFilter$1.doFilter(PluginServletFilter.java:163)
        at PluginClassLoader for locale//hudson.plugins.locale.LocaleFilter.doFilter(LocaleFilter.java:64)
        at hudson.util.PluginServletFilter$1.doFilter(PluginServletFilter.java:160)
        at PluginClassLoader for metrics//jenkins.metrics.impl.MetricsFilter.doFilter(MetricsFilter.java:125)
        at hudson.util.PluginServletFilter$1.doFilter(PluginServletFilter.java:160)
        at jenkins.util.HttpServletFilter$1.doFilter(HttpServletFilter.java:76)
        at hudson.util.PluginServletFilter$1.doFilter(PluginServletFilter.java:160)
        at hudson.util.PluginServletFilter.doFilter(PluginServletFilter.java:166)
        at Jenkins Main ClassLoader//org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:202)
        at Jenkins Main ClassLoader//org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1635)
        at jenkins.ErrorAttributeFilter.doFilter(ErrorAttributeFilter.java:29)
        at Jenkins Main ClassLoader//org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:202)
        at Jenkins Main ClassLoader//org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1635)
        at hudson.security.csrf.CrumbFilter.doFilter(CrumbFilter.java:160)
        at Jenkins Main ClassLoader//org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:202)
        at Jenkins Main ClassLoader//org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1635)
        at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:94)
        at PluginClassLoader for oic-auth//org.jenkinsci.plugins.oic.OicSecurityRealm$1.doFilter(OicSecurityRealm.java:640)
        at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:99)
        at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:94)
        at jenkins.security.AcegiSecurityExceptionFilter.doFilter(AcegiSecurityExceptionFilter.java:52)
        at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:99)
        at hudson.security.UnwrapSecurityExceptionFilter.doFilter(UnwrapSecurityExceptionFilter.java:54)
        at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:99)
        at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:126)
        at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:120)
        at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:99)
        at org.springframework.security.web.authentication.AnonymousAuthenticationFilter.doFilter(AnonymousAuthenticationFilter.java:100)
        at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:99)
        at org.springframework.security.web.authentication.rememberme.RememberMeAuthenticationFilter.doFilter(RememberMeAuthenticationFilter.java:145)
        at org.springframework.security.web.authentication.rememberme.RememberMeAuthenticationFilter.doFilter(RememberMeAuthenticationFilter.java:101)
        at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:99)
        at org.springframework.security.web.authentication.AbstractAuthenticationProcessingFilter.doFilter(AbstractAuthenticationProcessingFilter.java:227)
        at org.springframework.security.web.authentication.AbstractAuthenticationProcessingFilter.doFilter(AbstractAuthenticationProcessingFilter.java:221)
        at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:99)
        at jenkins.security.BasicHeaderProcessor.doFilter(BasicHeaderProcessor.java:97)
        at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:99)
        at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:117)
        at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:87)
        at hudson.security.HttpSessionContextIntegrationFilter2.doFilter(HttpSessionContextIntegrationFilter2.java:63)
        at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:99)
        at hudson.security.ChainedServletFilter.doFilter(ChainedServletFilter.java:111)
        at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:99)
        at hudson.security.ChainedServletFilter.doFilter(ChainedServletFilter.java:111)
        at hudson.security.HudsonFilter.doFilter(HudsonFilter.java:172)
        at Jenkins Main ClassLoader//org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:202)
        at Jenkins Main ClassLoader//org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1635)
        at org.kohsuke.stapler.compression.CompressionFilter.doFilter(CompressionFilter.java:53)
        at Jenkins Main ClassLoader//org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:202)
        at Jenkins Main ClassLoader//org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1635)
        at hudson.util.CharacterEncodingFilter.doFilter(CharacterEncodingFilter.java:86)
        at Jenkins Main ClassLoader//org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:202)
        at Jenkins Main ClassLoader//org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1635)
        at org.kohsuke.stapler.DiagnosticThreadNameFilter.doFilter(DiagnosticThreadNameFilter.java:31)
        at Jenkins Main ClassLoader//org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:202)
        at Jenkins Main ClassLoader//org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1635)
        at jenkins.security.SuspiciousRequestFilter.doFilter(SuspiciousRequestFilter.java:38)
        at Jenkins Main ClassLoader//org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:202)
        at Jenkins Main ClassLoader//org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1635)
        at Jenkins Main ClassLoader//org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:527)
        at Jenkins Main ClassLoader//org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:131)
        at Jenkins Main ClassLoader//org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:569)
        at Jenkins Main ClassLoader//org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:122)
        at Jenkins Main ClassLoader//org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:223)
        at Jenkins Main ClassLoader//org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1580)
        at Jenkins Main ClassLoader//org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:221)
        at Jenkins Main ClassLoader//org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1384)
        at Jenkins Main ClassLoader//org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:176)
        at Jenkins Main ClassLoader//org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:484)
        at Jenkins Main ClassLoader//org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1553)
        at Jenkins Main ClassLoader//org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:174)
        at Jenkins Main ClassLoader//org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1306)
        at Jenkins Main ClassLoader//org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:129)
        at Jenkins Main ClassLoader//org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:122)
        at Jenkins Main ClassLoader//org.eclipse.jetty.server.handler.gzip.GzipHandler.handle(GzipHandler.java:822)
        at Jenkins Main ClassLoader//org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:122)
        at Jenkins Main ClassLoader//org.eclipse.jetty.server.Server.handle(Server.java:563)
        at Jenkins Main ClassLoader//org.eclipse.jetty.server.HttpChannel$RequestDispatchable.dispatch(HttpChannel.java:1598)
        at Jenkins Main ClassLoader//org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:753)
        at Jenkins Main ClassLoader//org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:501)
        at Jenkins Main ClassLoader//org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:287)
        at Jenkins Main ClassLoader//org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:314)
        at Jenkins Main ClassLoader//org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:100)
        at Jenkins Main ClassLoader//org.eclipse.jetty.io.SelectableChannelEndPoint$1.run(SelectableChannelEndPoint.java:53)
        at Jenkins Main ClassLoader//org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.runTask(AdaptiveExecutionStrategy.java:421)
        at Jenkins Main ClassLoader//org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.consumeTask(AdaptiveExecutionStrategy.java:390)
        at Jenkins Main ClassLoader//org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.tryProduce(AdaptiveExecutionStrategy.java:277)
        at Jenkins Main ClassLoader//org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.run(AdaptiveExecutionStrategy.java:199)
        at Jenkins Main ClassLoader//org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:411)
        at Jenkins Main ClassLoader//org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:969)
        at Jenkins Main ClassLoader//org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.doRunJob(QueuedThreadPool.java:1194)
        at Jenkins Main ClassLoader//org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1149)
        at java.base/java.lang.Thread.run(Thread.java:829)
```

</details>

### Anything else?

**OIC configuration from server.xml (with redacted parts) :** 
<details>
  <summary>OCI configuration</summary>

```
  <securityRealm class="org.jenkinsci.plugins.oic.OicSecurityRealm" plugin="oic-auth@4.340.ve70636c6590e">
    <clientId>client-jenkins</clientId>
    <clientSecret>{***REDACTED***}</clientSecret>
    <tokenServerUrl>https://***REDACTED***/protocol/openid-connect/token</tokenServerUrl>
    <authorizationServerUrl>https://***REDACTED***/protocol/openid-connect/auth</authorizationServerUrl>
    <userInfoServerUrl>https://***REDACTED***/protocol/openid-connect/userinfo</userInfoServerUrl>
    <userNameField>preferred_username</userNameField>
    <fullNameFieldName>fullname</fullNameFieldName>
    <emailFieldName>email</emailFieldName>
    <groupsFieldName>groups</groupsFieldName>
    <scopes>openid profile roles email ***REDACTED***</scopes>
    <disableSslVerification>false</disableSslVerification>
    <logoutFromOpenidProvider>true</logoutFromOpenidProvider>
    <endSessionEndpoint>https://***REDACTED***/protocol/openid-connect/logout</endSessionEndpoint>
    <postLogoutRedirectUrl>https://jenkins.***REDACTED***</postLogoutRedirectUrl>
    <escapeHatchEnabled>true</escapeHatchEnabled>
    <escapeHatchUsername>***REDACTED***</escapeHatchUsername>
    <escapeHatchSecret>{***REDACTED***}</escapeHatchSecret>
    <escapeHatchGroup>admin</escapeHatchGroup>
    <useRefreshTokens>false</useRefreshTokens>
    <rootURLFromRequest>false</rootURLFromRequest>
    <sendScopesInTokenRequest>false</sendScopesInTokenRequest>
    <pkceEnabled>false</pkceEnabled>
    <disableTokenVerification>false</disableTokenVerification>
    <nonceDisabled>false</nonceDisabled>
    <tokenExpirationCheckDisabled>false</tokenExpirationCheckDisabled>
    <allowTokenAccessWithoutOicSession>false</allowTokenAccessWithoutOicSession>
  </securityRealm>
```

</details>

Something that might help is this warning I'm getting : 
```
WARNING o.j.plugins.oic.OicSecurityRealm#determineAuthorities: idToken and userInfo did not contain group field name: groups
```
The groups are currently not configured in Keycloak, it is either a local matrix or managed with a different authentication method (ldap)

**Comment by jtnord** [comment]
Your config is missing an entry that should have been present (
`<automanualconfigure>`) which was introduced 2 years ago.

if you save your config in the working version this should cause it to be saved, and then the migration should work as expected.

**Comment by Daryes** [comment]
Saving the configuration before updating did the trick, thanks

The following lines were inserted in the oic-auth `<securityRealm ...>` section when saving the configuration, before upgrading : 
```
22,23d21
>     <jwksServerUrl></jwksServerUrl>
>     <tokenAuthMethod>client_secret_post</tokenAuthMethod>
39d36
>     <automanualconfigure>manual</automanualconfigure>
48d44
>     <allowedTokenExpirationClockSkewSeconds>0</allowedTokenExpirationClockSkewSeconds>
```

Given the plugin is in the dedicated security page, it is possible others encounter the same situation : when everything is set, the options on this page do not really warrant going back an changing something on it.
As a suggestion, having those settings managed when missing by the migration would help.

For the record, I did another save on the panel as recommended after the upgrade, there was no change in the config.xml file.

**Comment by jtnord** [comment]
ok, I added a section about old configs to the release notes, so hopefully others will not fall into this.

> The following lines were inserted in the oic-auth <securityRealm ...> section when saving the configuration
> `<jwksServerUrl></jwksServerUrl>`

You should set this, or ensure that Token Validation is disabled.  (otherwise things are liable to break in future upgrades - without a jwksServerURL the keys to check the token are not available.

**Comment by jtnord** [comment]
because this is an issue with https://github.com/jenkinsci/oic-auth-plugin/releases/tag/4.350.v347c3b_8b_9d95 and https://github.com/jenkinsci/oic-auth-plugin/releases/tag/4.388.v4f73328eb_d2c requires users using manual config to upgrade to an interim release and configure the `issuer`, adding migration to the next version of the plugin will not help anyone in the future as they would already be locked out (because they need to upgrade to the security release to be able to set info, and the security release still contains the migration that believed the `autoManual` field would be present).
Whilst it could be possible to create a branch and create an intermediate release, given the updated release notes and simple work around I am not convinced this is worth it at this time.

I apologise for the unexpected breakage.

**Comment by Daryes** [comment]
No problem, the error message was explicit enough about the plugin name.
As the OIC configuration was in the config.xml main file, I just had to get my hands on the daily backup and rollback the plugin version.

For the Issuer field, unless I'm mistaken, it was not present before (long ago). 
It is currently not set on v4.371 after the migration, and working correctly without,

Just saw the requirements for the v4.388, gonna fix the empty fields. 
Or switch to the well-known endpoint, it gave some trouble before, but is fixed since. Just need to update the configuration on the clients .
Thanks.
