### ISSUE TITLE
Improve the description for configuration-as-code (casc) plugin: logoutFromOpenidProvider not marked as required

### ISSUE THREAD

**Issue by li9x** [jenkinsci/oic-auth-plugin#71]
In the reference page of CasC the **logoutFromOpenidProvider** key is not described as _required_. But not setting that boolean leads to Jenkins not being reachable because of a NPE, see log below, last line.

Since we're building Jenkins with a custom set of plugins, creating a docker image and deploying it to multiple k8s, we're heavily relying on the CasC plugin. Since the option to _Logout of from the OpenID Provider_ is set to false by default **when installing the plugin via the UI**, I'd suggest to change the option for CasC to false by default as well.
The other option of course is to just fix the description for CasC and add "Required".

`...
Caused by: io.jenkins.plugins.casc.ConfiguratorException: oic: Failed to construct instance of class org.jenkinsci.plugins.oic.OicSecurityRealm.
 Constructor: public org.jenkinsci.plugins.oic.OicSecurityRealm(java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String,boolean,java.lang.Boolean,java.lang.String,java.lang.String,boolean,java.lang.String,java.lang.String,java.lang.String,java.lang.String) throws java.io.IOException.
 Arguments: [java.lang.String, java.lang.String, null, java.lang.String, java.lang.String, java.lang.String, null, null, null, null, null, java.lang.String, null, java.lang.Boolean, null, java.lang.String, null, java.lang.Boolean, null, null, null, null]
	at io.jenkins.plugins.casc.impl.configurators.DataBoundConfigurator.tryConstructor(DataBoundConfigurator.java:149)
	at io.jenkins.plugins.casc.impl.configurators.DataBoundConfigurator.instance(DataBoundConfigurator.java:73)
	at io.jenkins.plugins.casc.BaseConfigurator.configure(BaseConfigurator.java:262)
	at io.jenkins.plugins.casc.impl.configurators.DataBoundConfigurator.configure(DataBoundConfigurator.java:79)
	at io.jenkins.plugins.casc.impl.configurators.HeteroDescribableConfigurator.lambda$doConfigure$16668e2$1(HeteroDescribableConfigurator.java:225)
	at io.vavr.CheckedFunction0.lambda$unchecked$52349c75$1(CheckedFunction0.java:201)
	at io.jenkins.plugins.casc.impl.configurators.HeteroDescribableConfigurator.doConfigure(HeteroDescribableConfigurator.java:225)
	at io.jenkins.plugins.casc.impl.configurators.HeteroDescribableConfigurator.lambda$null$2(HeteroDescribableConfigurator.java:81)
	at io.vavr.control.Option.map(Option.java:373)
	at io.jenkins.plugins.casc.impl.configurators.HeteroDescribableConfigurator.lambda$configure$3(HeteroDescribableConfigurator.java:81)
	at io.vavr.Tuple2.apply(Tuple2.java:239)
	at io.jenkins.plugins.casc.impl.configurators.HeteroDescribableConfigurator.configure(HeteroDescribableConfigurator.java:78)
	at io.jenkins.plugins.casc.impl.configurators.HeteroDescribableConfigurator.check(HeteroDescribableConfigurator.java:87)
	at io.jenkins.plugins.casc.impl.configurators.HeteroDescribableConfigurator.check(HeteroDescribableConfigurator.java:50)
	at io.jenkins.plugins.casc.BaseConfigurator.configure(BaseConfigurator.java:347)
	at io.jenkins.plugins.casc.BaseConfigurator.check(BaseConfigurator.java:282)
	at io.jenkins.plugins.casc.ConfigurationAsCode.lambda$checkWith$6(ConfigurationAsCode.java:644)
	at io.jenkins.plugins.casc.ConfigurationAsCode.invokeWith(ConfigurationAsCode.java:606)
	... 18 more
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at io.jenkins.plugins.casc.impl.configurators.DataBoundConfigurator.tryConstructor(DataBoundConfigurator.java:141)
	... 35 more
Caused by: java.lang.NullPointerException
	at org.jenkinsci.plugins.oic.OicSecurityRealm.<init>(OicSecurityRealm.java:154)
	... 40 more`

**Comment by michael-doubez** [comment]
I suspect it was fixed earlier but unit test and code added to have minimal JasC config
