### ISSUE TITLE
NullPointerException when no idtoken is returned

### ISSUE THREAD

**Issue by damianslee** [jenkinsci/oic-auth-plugin#92]
I'm configuring the OpenID Connect plugin with a Oauth2 user login with ArcGIS Portal 

I get a null reference exception with openid in or removed from the scope.

The sign in is successful; and the /finishLogin request is follows
GET /jenkins/securityRealm/finishLogin?code=<token>&state=<somestate> HTTP/1.1

Then i believe there is a call to the /token endpoint
This documentation of the ArcGIS Portal OAUTH2 response_type=code flow
https://developers.arcgis.com/documentation/core-concepts/security-and-authentication/server-based-user-logins/

{
    "access_token"<accesstoken>",
    "expires_in": 1800,
    "refresh_token": "<refresh token>",
    "username": "damian"
}

The exception received is as follows
java.lang.NullPointerException
	at com.google.api.client.json.webtoken.JsonWebSignature$Parser.parse(JsonWebSignature.java:598)
	at com.google.api.client.auth.openidconnect.IdToken.parse(IdToken.java:155)
	at org.jenkinsci.plugins.oic.OicSecurityRealm$3.onSuccess(OicSecurityRealm.java:398)
	at org.jenkinsci.plugins.oic.OicSession.doFinishLogin(OicSession.java:110)
	at org.jenkinsci.plugins.oic.OicSecurityRealm.doFinishLogin(OicSecurityRealm.java:657)
	at java.lang.invoke.MethodHandle.invokeWithArguments(Unknown Source)
	at org.kohsuke.stapler.Function$MethodFunction.invoke(Function.java:396)
	at org.kohsuke.stapler.Function$InstanceFunction.invoke(Function.java:408)
	at org.kohsuke.stapler.Function.bindAndInvoke(Function.java:212)
	at org.kohsuke.stapler.Function.bindAndInvokeAndServeResponse(Function.java:145)
	at org.kohsuke.stapler.MetaClass$11.doDispatch(MetaClass.java:535)
	at org.kohsuke.stapler.NameBasedDispatcher.dispatch(NameBasedDispatcher.java:58)
	at org.kohsuke.stapler.Stapler.tryInvoke(Stapler.java:747)

Looking at the code, there is no null check when getting IdToken, event when openid is excluded from the <scopes>
 IdToken idToken = IdToken.parse(JSON_FACTORY, response.getIdToken());

**Comment by j14ncn** [comment]
I have the same problem. ; (

**Comment by j14ncn** [comment]
I have the same issue. ; (

**Comment by icecreamtan** [comment]
I have the same issue too

**Comment by michael-doubez** [comment]
This looks like a non compliant OIDC
https://openid.net/specs/openid-connect-core-1_0.html#TokenResponse

Can you please provide more context ? (dump of requests/answers, scope required ...)

**Comment by michael-doubez** [comment]
no answer
