### ISSUE TITLE
Cannot finish Login

### ISSUE THREAD

**Issue by Andrei-Stepanov** [jenkinsci/oic-auth-plugin#96]
Hello, the plugin cannot finish login with next trace:

```
Stack trace
java.lang.IllegalArgumentException: expected primitive class, but got: java.util.List<java.lang.String>
	at com.google.api.client.util.Data.parsePrimitiveValue(Data.java:453)
	at com.google.api.client.json.JsonParser.parseValue(JsonParser.java:859)
Caused: java.lang.IllegalArgumentException: key amr, field private java.util.List com.google.api.client.auth.openidconnect.IdToken$Payload.methodsReferences
	at com.google.api.client.json.JsonParser.parseValue(JsonParser.java:889)
	at com.google.api.client.json.JsonParser.parse(JsonParser.java:472)
	at com.google.api.client.json.JsonParser.parseValue(JsonParser.java:781)
Caused: java.lang.IllegalArgumentException: key amr
	at com.google.api.client.json.JsonParser.parseValue(JsonParser.java:889)
	at com.google.api.client.json.JsonParser.parse(JsonParser.java:382)
	at com.google.api.client.json.JsonParser.parse(JsonParser.java:336)
	at com.google.api.client.json.JsonParser.parseAndClose(JsonParser.java:166)
	at com.google.api.client.json.JsonParser.parseAndClose(JsonParser.java:148)
	at com.google.api.client.json.JsonFactory.fromInputStream(JsonFactory.java:206)
	at com.google.api.client.json.webtoken.JsonWebSignature$Parser.parse(JsonWebSignature.java:612)
	at com.google.api.client.auth.openidconnect.IdToken.parse(IdToken.java:155)
	at org.jenkinsci.plugins.oic.OicSecurityRealm$3.onSuccess(OicSecurityRealm.java:398)
	at org.jenkinsci.plugins.oic.OicSession.doFinishLogin(OicSession.java:110)
	at org.jenkinsci.plugins.oic.OicSecurityRealm.doFinishLogin(OicSecurityRealm.java:657)
	at java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:627)
	at org.kohsuke.stapler.Function$MethodFunction.invoke(Function.java:396)
```

URL is: https://xxxxx.org/securityRealm/finishLogin?code=xxxxxx-0601-42d5-bc79-5fa2fa824d4d_PBsdcfjI8iRqBdaLlpGgFZQ3bjJFwRRX&state=XDk4NDM3OWQtMDYwMS00

It fails at:
```
                    IdToken idToken = IdToken.parse(JSON_FACTORY, response.getIdToken());
```

Could you please give a hint?
Thank you.

**Comment by Andrei-Stepanov** [comment]
I opened issue also at https://github.com/googleapis/google-oauth-java-client/issues/471
But, if you know how to fix, please help.
Thank you.

**Comment by Andrei-Stepanov** [comment]
Issue on Idp side:
https://pagure.io/ipsilon/issue/339
Closing bug.
