### ISSUE TITLE
Connection Refused Exception when trying to connect to standalone keycloak

### ISSUE THREAD

**Issue by RaviChandraVeeramachaneni** [jenkinsci/oic-auth-plugin#98]
This recently happens for standalone testing also. I am not sure what's the problem but my code looks like below
``` ClientRepresentation client = new ClientRepresentation();
client.setClientId(properties.getClientId());
client.setClientAuthenticatorType(CLIENT_SECRET);
if (redirectURL != null && !redirectURL.trim().isEmpty()) {
client.setRedirectUris(Collections.singletonList(redirectURL));
} else {
client.setRedirectUris(null);
}
client.setWebOrigins(Collections.singletonList("+"));
client.setDirectAccessGrantsEnabled(false);
client.setProtocol(OIDC_CONNECT_PROTOCOL);
client.setEnabled(enabled);
client.setConsentRequired(false);
//client.setBearerOnly(false);
//client.setPublicClient(true);
if ("public".equals(type)) {
client.setBearerOnly(false);
client.setPublicClient(true);
} else if ("bearer-only".equals(type)) {
client.setBearerOnly(true);
client.setPublicClient(false);
} else {
// Fallback to "confidential"
client.setBearerOnly(false);
client.setPublicClient(false);
}
client.setId(clientName);
client.setName(clientName);

    //Create the client with the ClientRepresentation object
    Response response = keycloak.realm(properties.getRealm()).clients().create(client);
    String errorMessage = response.readEntity(String.class);

    if (response.getStatus() != HttpStatus.SC_CREATED) {
        if (response.getStatus() == HttpStatus.SC_CONFLICT) {
            throw Error.ERROR_DUPLICATE_KEYCLOAK_ENTRY.with(errorMessage);
        } else {
            throw Error.ERROR_CREATING_KEYCLOAK_ENTRY.with(errorMessage);
        }
    }

    //Retrieve secret using ClientsResource since the bug in the ClientRepresentation Object is not allowing the fetch the secret directly.
    ClientRepresentation clientCreated = keycloak.realm(properties.getRealm()).clients().findByClientId(properties.getClientId()).get(0);
    String clientSecret = keycloak.realm(properties.getRealm()).clients().get(clientCreated.getId()).getSecret().getValue();

    return clientSecret;``
The exception occurs at this line Response response = keycloak.realm(properties.getRealm()).clients().create(client); and the log is so poor to understand further except it says connection refused.

javax.ws.rs.ProcessingException: RESTEASY004655: Unable to invoke request: org.apache.http.conn.HttpHostConnectException: Connect to keycloak:8090 [keycloak/172.31.0.5] failed: Connection refused (Connection refused)
Caused by: java.net.ConnectException: Connection refused (Connection refused)
at java.base/java.net.PlainSocketImpl.socketConnect(Native Method)
at java.base/java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:399)
at java.base/java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:242)
at java.base/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:224)
at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:403)
at java.base/java.net.Socket.connect(Socket.java:609)
at org.apache.httpcomponents.core//org.apache.http.conn.socket.PlainConnectionSocketFactory.connectSocket(PlainConnectionSocketFactory.java:75)
at org.apache.httpcomponents.core//org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:142)

Code Credit Mostly to : Keycloak Docs & programcreek.com

**Comment by michael-doubez** [comment]
Not related to plugin AFAIS
